-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('NEW_BOOKING', 'BOOKING_CANCELLED', 'BOOKING_CONFIRMED', 'PAYMENT_RECEIVED', 'REPORT_UPLOADED', 'APPOINTMENT_REMINDER', 'CONSULTANT_RESPONSE', 'WITHDRAWAL_REQUESTED', 'ADMIN_ALERT', 'SYSTEM_NOTIFICATION') NOT NULL;
